"""create table

Revision ID: 2c29aa7b20be
Revises: 
Create Date: 2022-08-28 08:43:22.985144

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2c29aa7b20be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fights',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('start', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_fights_id'), 'fights', ['id'], unique=False)
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=30), nullable=True),
                    sa.Column('password_hash', sa.String(), nullable=False),
                    sa.Column('fight_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['fight_id'], ['fights.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_fight_id'), 'users', ['fight_id'],
                    unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'],
                    unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_fight_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_fights_id'), table_name='fights')
    op.drop_table('fights')
    # ### end Alembic commands ###
