"""1 migrate

Revision ID: 43d53b93904c
Revises: 
Create Date: 2022-09-04 12:26:03.657104

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '43d53b93904c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'fights',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column(
            'start', sa.DateTime(), server_default=sa.text('now()'),
            nullable=True
        ),
        sa.Column(
            'token', sa.String(length=500), server_default='', nullable=True
        ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fights_id'), 'fights', ['id'], unique=False)
    op.create_table(
        'fight_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'time', sa.DateTime(), server_default=sa.text('now()'),
            nullable=True
        ),
        sa.Column('fight_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['fight_id'], ['fights.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_fight_history_fight_id'), 'fight_history', ['fight_id'],
        unique=False
    )
    op.create_index(
        op.f('ix_fight_history_id'), 'fight_history', ['id'], unique=False
    )
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=30), nullable=True),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column('ready_to_fight', sa.Boolean(), nullable=True),
        sa.Column('fight_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['fight_id'], ['fights.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_users_fight_id'), 'users', ['fight_id'], unique=False
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(
        op.f('ix_users_username'), 'users', ['username'], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_fight_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_fight_history_id'), table_name='fight_history')
    op.drop_index(
        op.f('ix_fight_history_fight_id'), table_name='fight_history'
    )
    op.drop_table('fight_history')
    op.drop_index(op.f('ix_fights_id'), table_name='fights')
    op.drop_table('fights')
    # ### end Alembic commands ###
