interface Tank.Operations.IMovable
{
    Vector getPosition();
    Vector setPosition(Vector newValue);
    Vector getVelocity();
}


class AutoGenerated.MovableAdapter: Tank.Operations.IMovable
{
    UObject obj;
    public MovableAdapter(UObject obj)
    {
        this.obj = obj;
    }

    public Vector getPosition()
    {
        return IoC.Resolve("Tank.Operations.IMovable:position.get", obj);
    }

    public Vector getVelocity()
    {
        return IoC.Resolve("Tank.Operations.IMovable:velocity.get", obj);
    }

    public Vector setPosition(Vector newValue)
    {
        return IoC.Resolve("Tank.Operations.IMovable:position.set", obj, newValue);
    }
}

var adapter = IoC.Resolve("Adapter", typeof(IMovable), obj);
